Add requirements-dev.txt
Qiskit/qiskit-tutorials pull request #1323
Opened 2022-05-19 09:21 UTC by bopardikarsoham

I have added a `requirements-dev.txt` file as per Issue https://github.com/Qiskit/qiskit-tutorials/issues/1317. This contains all the packages used in the `qiskit-tutorials` repo. I also double-checked all of the packages required for this repository.

2022-05-19 09:23 UTC, HuangJunye commented
Thanks! Can you try to do a local build with sphinx with a fresh environment to check that this file contains all and only necessary packages?

2022-05-19 09:26 UTC, bopardikarsoham commented
Sure, I'll test it out locally

2022-05-19 09:41 UTC, bopardikarsoham commented
@HuangJunye I have tested it locally by creating a new virtual environment in my PC and installing all the packages from scratch in the requirements-dev.txt file through the pip install -r requirements-dev.txt. The packages were successfully installed and everything seems to be working including sphinx thumbnails.

2022-05-19 10:37 UTC, HuangJunye commented
@bopardikarsoham That's awesome! I am having some troubles do a local build on my machine. https://github.com/Qiskit/qiskit-tutorials/issues/1324 

I think a lot of these requirements are already in qiskit and qiskit[visualization]. Can you try this simplified version?

```
qiskit
jupyter
sphinx
nbsphinx
sphinx_rtd_theme
networkx
scikit-learn
matplotlib
qiskit[visualization]
cvxpy
pyscf
graphviz
```
I had a look at the CI and I think these should be sufficient based on https://github.com/Qiskit/qiskit-tutorials/blob/c98b29af9ca4350a940f5e48b911ffb4f1be5557/azure-pipelines.yml#L39-L43 The only missing requirement would be pandoc but it's not pip installable because it's not a python package.

2022-05-19 11:22 UTC, bopardikarsoham commented
Yes @HuangJunye , I believe this list is sufficient and capable of installing all of the packages required for this repo to function. I figured that out too in the pipelines file.

2022-05-19 11:39 UTC, bopardikarsoham commented
> @bopardikarsoham That's awesome! I am having some troubles making a local build on my machine. #1324
> 
> I think a lot of these requirements are already in qiskit and qiskit[visualization]. Can you try this simplified version?
> 
> ```
> qiskit
> jupyter
> sphinx
> nbsphinx
> sphinx_rtd_theme
> networkx
> scikit-learn
> matplotlib
> qiskit[visualization]
> cvxpy
> pyscf
> graphviz
> ```
> 
> I had a look at the CI and I think these should be sufficient based on
> 
> https://github.com/Qiskit/qiskit-tutorials/blob/c98b29af9ca4350a940f5e48b911ffb4f1be5557/azure-pipelines.yml#L39-L43
> 
> The only missing requirement would be pandoc but it's not pip installable because it's not a python package.

Replacing `graphviz` with `pydot` will fix everything

2022-05-19 13:08 UTC, mtreinish commented
graphviz isn't a python dependency and can not be listed in a requirements list as pip will not be able to install it for you. It is something you have to install separately through a different mechanism (see: https://graphviz.org/download/ )

2022-05-19 14:38 UTC, HuangJunye requested changes
I made a suggestion to change. I tested on macOS and it's working together with conda install pandoc and graphviz.

2022-05-22 18:58 UTC, bopardikarsoham commented on requirements-dev.txt
> +docplex
Yes I have updated the PR accordingly!

2022-05-23 08:23 UTC, HuangJunye approved these changes
LGTM. Thank you!

2022-05-23 08:24 UTC, merged